language: android

jdk:
    - oraclejdk8

android:
    components:
        - tools
        - build-tools-24.0.0
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services
    licenses:
        - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean test jacocoTestReport build
    - ./gradlew java:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false
    - ./gradlew android:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

after_success:
  - bash <(curl -s https://codecov.io/bash)
