language: android

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

before_deploy:
  - chmod +rx tools

deploy:
  - provider: script
    script: ./tools/bash-bintray-upload.sh $BINTRAY_USER $BINTRAY_KEY false
    skip_cleanup: true
    on:
      branch: master

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)
